# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/grpc/group_service/group_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*src/grpc/group_service/group_service.proto\x12\rgroup_service\x1a\x1bgoogle/protobuf/empty.proto\">\n\x0bGroupAddDTO\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\ngroup_name\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"3\n\x1eGetGroupsNameByUserNameRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\"6\n\x1fGetGroupsNameByUserNameResponse\x12\x13\n\x0bgroup_names\x18\x01 \x03(\t\"C\n\x12\x43reateGroupRequest\x12-\n\tnew_group\x18\x01 \x01(\x0b\x32\x1a.group_service.GroupAddDTO\"2\n\x1cGetGroupIdByGroupNameRequest\x12\x12\n\ngroup_name\x18\x01 \x01(\t\"1\n\x1dGetGroupIdByGroupNameResponse\x12\x10\n\x08group_id\x18\x01 \x01(\t\"+\n\x15IsGroupCreatedRequest\x12\x12\n\ngroup_name\x18\x01 \x01(\t\")\n\x16IsGroupCreatedResponse\x12\x0f\n\x07\x63reated\x18\x01 \x01(\x08\">\n\x12UpdateGroupRequest\x12\x10\n\x08group_id\x18\x01 \x01(\t\x12\x16\n\x0enew_group_name\x18\x02 \x01(\t\"&\n\x12\x44\x65leteGroupRequest\x12\x10\n\x08group_id\x18\x01 \x01(\t2\xc8\x04\n\x0cGroupService\x12}\n\x1cget_groups_name_by_user_name\x12-.group_service.GetGroupsNameByUserNameRequest\x1a..group_service.GetGroupsNameByUserNameResponse\x12I\n\x0c\x63reate_group\x12!.group_service.CreateGroupRequest\x1a\x16.google.protobuf.Empty\x12w\n\x1aget_group_id_by_group_name\x12+.group_service.GetGroupIdByGroupNameRequest\x1a,.group_service.GetGroupIdByGroupNameResponse\x12_\n\x10is_group_created\x12$.group_service.IsGroupCreatedRequest\x1a%.group_service.IsGroupCreatedResponse\x12I\n\x0cupdate_group\x12!.group_service.UpdateGroupRequest\x1a\x16.google.protobuf.Empty\x12I\n\x0c\x64\x65lete_group\x12!.group_service.DeleteGroupRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.grpc.group_service.group_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GROUPADDDTO']._serialized_start=90
  _globals['_GROUPADDDTO']._serialized_end=152
  _globals['_GETGROUPSNAMEBYUSERNAMEREQUEST']._serialized_start=154
  _globals['_GETGROUPSNAMEBYUSERNAMEREQUEST']._serialized_end=205
  _globals['_GETGROUPSNAMEBYUSERNAMERESPONSE']._serialized_start=207
  _globals['_GETGROUPSNAMEBYUSERNAMERESPONSE']._serialized_end=261
  _globals['_CREATEGROUPREQUEST']._serialized_start=263
  _globals['_CREATEGROUPREQUEST']._serialized_end=330
  _globals['_GETGROUPIDBYGROUPNAMEREQUEST']._serialized_start=332
  _globals['_GETGROUPIDBYGROUPNAMEREQUEST']._serialized_end=382
  _globals['_GETGROUPIDBYGROUPNAMERESPONSE']._serialized_start=384
  _globals['_GETGROUPIDBYGROUPNAMERESPONSE']._serialized_end=433
  _globals['_ISGROUPCREATEDREQUEST']._serialized_start=435
  _globals['_ISGROUPCREATEDREQUEST']._serialized_end=478
  _globals['_ISGROUPCREATEDRESPONSE']._serialized_start=480
  _globals['_ISGROUPCREATEDRESPONSE']._serialized_end=521
  _globals['_UPDATEGROUPREQUEST']._serialized_start=523
  _globals['_UPDATEGROUPREQUEST']._serialized_end=585
  _globals['_DELETEGROUPREQUEST']._serialized_start=587
  _globals['_DELETEGROUPREQUEST']._serialized_end=625
  _globals['_GROUPSERVICE']._serialized_start=628
  _globals['_GROUPSERVICE']._serialized_end=1212
# @@protoc_insertion_point(module_scope)
