# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from src.grpc.group_service import group_service_pb2 as src_dot_grpc_dot_group__service_dot_group__service__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in src/grpc/group_service/group_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class GroupServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_groups_name_by_user_name = channel.unary_unary(
                '/group_service.GroupService/get_groups_name_by_user_name',
                request_serializer=src_dot_grpc_dot_group__service_dot_group__service__pb2.GetGroupsNameByUserNameRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_group__service_dot_group__service__pb2.GetGroupsNameByUserNameResponse.FromString,
                _registered_method=True)
        self.create_group = channel.unary_unary(
                '/group_service.GroupService/create_group',
                request_serializer=src_dot_grpc_dot_group__service_dot_group__service__pb2.CreateGroupRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.get_group_id_by_group_name = channel.unary_unary(
                '/group_service.GroupService/get_group_id_by_group_name',
                request_serializer=src_dot_grpc_dot_group__service_dot_group__service__pb2.GetGroupIdByGroupNameRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_group__service_dot_group__service__pb2.GetGroupIdByGroupNameResponse.FromString,
                _registered_method=True)
        self.is_group_created = channel.unary_unary(
                '/group_service.GroupService/is_group_created',
                request_serializer=src_dot_grpc_dot_group__service_dot_group__service__pb2.IsGroupCreatedRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_group__service_dot_group__service__pb2.IsGroupCreatedResponse.FromString,
                _registered_method=True)
        self.update_group = channel.unary_unary(
                '/group_service.GroupService/update_group',
                request_serializer=src_dot_grpc_dot_group__service_dot_group__service__pb2.UpdateGroupRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.delete_group = channel.unary_unary(
                '/group_service.GroupService/delete_group',
                request_serializer=src_dot_grpc_dot_group__service_dot_group__service__pb2.DeleteGroupRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class GroupServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_groups_name_by_user_name(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create_group(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_group_id_by_group_name(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_group_created(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_group(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_group(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GroupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_groups_name_by_user_name': grpc.unary_unary_rpc_method_handler(
                    servicer.get_groups_name_by_user_name,
                    request_deserializer=src_dot_grpc_dot_group__service_dot_group__service__pb2.GetGroupsNameByUserNameRequest.FromString,
                    response_serializer=src_dot_grpc_dot_group__service_dot_group__service__pb2.GetGroupsNameByUserNameResponse.SerializeToString,
            ),
            'create_group': grpc.unary_unary_rpc_method_handler(
                    servicer.create_group,
                    request_deserializer=src_dot_grpc_dot_group__service_dot_group__service__pb2.CreateGroupRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'get_group_id_by_group_name': grpc.unary_unary_rpc_method_handler(
                    servicer.get_group_id_by_group_name,
                    request_deserializer=src_dot_grpc_dot_group__service_dot_group__service__pb2.GetGroupIdByGroupNameRequest.FromString,
                    response_serializer=src_dot_grpc_dot_group__service_dot_group__service__pb2.GetGroupIdByGroupNameResponse.SerializeToString,
            ),
            'is_group_created': grpc.unary_unary_rpc_method_handler(
                    servicer.is_group_created,
                    request_deserializer=src_dot_grpc_dot_group__service_dot_group__service__pb2.IsGroupCreatedRequest.FromString,
                    response_serializer=src_dot_grpc_dot_group__service_dot_group__service__pb2.IsGroupCreatedResponse.SerializeToString,
            ),
            'update_group': grpc.unary_unary_rpc_method_handler(
                    servicer.update_group,
                    request_deserializer=src_dot_grpc_dot_group__service_dot_group__service__pb2.UpdateGroupRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'delete_group': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_group,
                    request_deserializer=src_dot_grpc_dot_group__service_dot_group__service__pb2.DeleteGroupRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'group_service.GroupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('group_service.GroupService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GroupService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_groups_name_by_user_name(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/group_service.GroupService/get_groups_name_by_user_name',
            src_dot_grpc_dot_group__service_dot_group__service__pb2.GetGroupsNameByUserNameRequest.SerializeToString,
            src_dot_grpc_dot_group__service_dot_group__service__pb2.GetGroupsNameByUserNameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def create_group(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/group_service.GroupService/create_group',
            src_dot_grpc_dot_group__service_dot_group__service__pb2.CreateGroupRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_group_id_by_group_name(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/group_service.GroupService/get_group_id_by_group_name',
            src_dot_grpc_dot_group__service_dot_group__service__pb2.GetGroupIdByGroupNameRequest.SerializeToString,
            src_dot_grpc_dot_group__service_dot_group__service__pb2.GetGroupIdByGroupNameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def is_group_created(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/group_service.GroupService/is_group_created',
            src_dot_grpc_dot_group__service_dot_group__service__pb2.IsGroupCreatedRequest.SerializeToString,
            src_dot_grpc_dot_group__service_dot_group__service__pb2.IsGroupCreatedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update_group(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/group_service.GroupService/update_group',
            src_dot_grpc_dot_group__service_dot_group__service__pb2.UpdateGroupRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_group(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/group_service.GroupService/delete_group',
            src_dot_grpc_dot_group__service_dot_group__service__pb2.DeleteGroupRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
