# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from src.grpc.word_type_service import word_type_service_pb2 as src_dot_grpc_dot_word__type__service_dot_word__type__service__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in src/grpc/word_type_service/word_type_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class WordTypeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_word_type = channel.unary_unary(
                '/word_type_service.WordTypeService/create_word_type',
                request_serializer=src_dot_grpc_dot_word__type__service_dot_word__type__service__pb2.CreateWordTypeRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_word__type__service_dot_word__type__service__pb2.CreateWordTypeResponse.FromString,
                _registered_method=True)
        self.get_word_type_id = channel.unary_unary(
                '/word_type_service.WordTypeService/get_word_type_id',
                request_serializer=src_dot_grpc_dot_word__type__service_dot_word__type__service__pb2.GetWordTypeIdRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_word__type__service_dot_word__type__service__pb2.GetWordTypeIdResponse.FromString,
                _registered_method=True)
        self.update_word_type = channel.unary_unary(
                '/word_type_service.WordTypeService/update_word_type',
                request_serializer=src_dot_grpc_dot_word__type__service_dot_word__type__service__pb2.UpdateWordTypeRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.delete_word_type = channel.unary_unary(
                '/word_type_service.WordTypeService/delete_word_type',
                request_serializer=src_dot_grpc_dot_word__type__service_dot_word__type__service__pb2.DeleteWordTypeRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class WordTypeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create_word_type(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_word_type_id(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_word_type(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_word_type(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WordTypeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create_word_type': grpc.unary_unary_rpc_method_handler(
                    servicer.create_word_type,
                    request_deserializer=src_dot_grpc_dot_word__type__service_dot_word__type__service__pb2.CreateWordTypeRequest.FromString,
                    response_serializer=src_dot_grpc_dot_word__type__service_dot_word__type__service__pb2.CreateWordTypeResponse.SerializeToString,
            ),
            'get_word_type_id': grpc.unary_unary_rpc_method_handler(
                    servicer.get_word_type_id,
                    request_deserializer=src_dot_grpc_dot_word__type__service_dot_word__type__service__pb2.GetWordTypeIdRequest.FromString,
                    response_serializer=src_dot_grpc_dot_word__type__service_dot_word__type__service__pb2.GetWordTypeIdResponse.SerializeToString,
            ),
            'update_word_type': grpc.unary_unary_rpc_method_handler(
                    servicer.update_word_type,
                    request_deserializer=src_dot_grpc_dot_word__type__service_dot_word__type__service__pb2.UpdateWordTypeRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'delete_word_type': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_word_type,
                    request_deserializer=src_dot_grpc_dot_word__type__service_dot_word__type__service__pb2.DeleteWordTypeRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'word_type_service.WordTypeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('word_type_service.WordTypeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WordTypeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create_word_type(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/word_type_service.WordTypeService/create_word_type',
            src_dot_grpc_dot_word__type__service_dot_word__type__service__pb2.CreateWordTypeRequest.SerializeToString,
            src_dot_grpc_dot_word__type__service_dot_word__type__service__pb2.CreateWordTypeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_word_type_id(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/word_type_service.WordTypeService/get_word_type_id',
            src_dot_grpc_dot_word__type__service_dot_word__type__service__pb2.GetWordTypeIdRequest.SerializeToString,
            src_dot_grpc_dot_word__type__service_dot_word__type__service__pb2.GetWordTypeIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update_word_type(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/word_type_service.WordTypeService/update_word_type',
            src_dot_grpc_dot_word__type__service_dot_word__type__service__pb2.UpdateWordTypeRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_word_type(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/word_type_service.WordTypeService/delete_word_type',
            src_dot_grpc_dot_word__type__service_dot_word__type__service__pb2.DeleteWordTypeRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
