# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/grpc/word_type_service/word_type_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2src/grpc/word_type_service/word_type_service.proto\x12\x11word_type_service\x1a\x1bgoogle/protobuf/empty.proto\"*\n\x15\x43reateWordTypeRequest\x12\x11\n\tword_type\x18\x01 \x01(\t\".\n\x16\x43reateWordTypeResponse\x12\x14\n\x0cword_type_id\x18\x01 \x01(\t\")\n\x14GetWordTypeIdRequest\x12\x11\n\tword_type\x18\x01 \x01(\t\"-\n\x15GetWordTypeIdResponse\x12\x14\n\x0cword_type_id\x18\x01 \x01(\t\"D\n\x15UpdateWordTypeRequest\x12\x14\n\x0cword_type_id\x18\x01 \x01(\t\x12\x15\n\rnew_word_type\x18\x02 \x01(\t\"-\n\x15\x44\x65leteWordTypeRequest\x12\x14\n\x0cword_type_id\x18\x01 \x01(\t*G\n\x0cWordTypeEnum\x12\t\n\x05\x42\x41SIC\x10\x00\x12\x0c\n\x08STANDARD\x10\x01\x12\n\n\x06\x43USTOM\x10\x02\x12\x12\n\x0eTEST_WORD_TYPE\x10\x03\x32\x8d\x03\n\x0fWordTypeService\x12g\n\x10\x63reate_word_type\x12(.word_type_service.CreateWordTypeRequest\x1a).word_type_service.CreateWordTypeResponse\x12\x65\n\x10get_word_type_id\x12\'.word_type_service.GetWordTypeIdRequest\x1a(.word_type_service.GetWordTypeIdResponse\x12T\n\x10update_word_type\x12(.word_type_service.UpdateWordTypeRequest\x1a\x16.google.protobuf.Empty\x12T\n\x10\x64\x65lete_word_type\x12(.word_type_service.DeleteWordTypeRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.grpc.word_type_service.word_type_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORDTYPEENUM']._serialized_start=401
  _globals['_WORDTYPEENUM']._serialized_end=472
  _globals['_CREATEWORDTYPEREQUEST']._serialized_start=102
  _globals['_CREATEWORDTYPEREQUEST']._serialized_end=144
  _globals['_CREATEWORDTYPERESPONSE']._serialized_start=146
  _globals['_CREATEWORDTYPERESPONSE']._serialized_end=192
  _globals['_GETWORDTYPEIDREQUEST']._serialized_start=194
  _globals['_GETWORDTYPEIDREQUEST']._serialized_end=235
  _globals['_GETWORDTYPEIDRESPONSE']._serialized_start=237
  _globals['_GETWORDTYPEIDRESPONSE']._serialized_end=282
  _globals['_UPDATEWORDTYPEREQUEST']._serialized_start=284
  _globals['_UPDATEWORDTYPEREQUEST']._serialized_end=352
  _globals['_DELETEWORDTYPEREQUEST']._serialized_start=354
  _globals['_DELETEWORDTYPEREQUEST']._serialized_end=399
  _globals['_WORDTYPESERVICE']._serialized_start=475
  _globals['_WORDTYPESERVICE']._serialized_end=872
# @@protoc_insertion_point(module_scope)
