# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from src.grpc.level_service import level_service_pb2 as src_dot_grpc_dot_level__service_dot_level__service__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in src/grpc/level_service/level_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class LevelServiceGRPCStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_levels = channel.unary_unary(
                '/levels.LevelServiceGRPC/create_levels',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.get_levels = channel.unary_unary(
                '/levels.LevelServiceGRPC/get_levels',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelList.FromString,
                _registered_method=True)
        self.create_level = channel.unary_unary(
                '/levels.LevelServiceGRPC/create_level',
                request_serializer=src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.get_level_id_by_name = channel.unary_unary(
                '/levels.LevelServiceGRPC/get_level_id_by_name',
                request_serializer=src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelIdResponse.FromString,
                _registered_method=True)
        self.get_level_by_id = channel.unary_unary(
                '/levels.LevelServiceGRPC/get_level_by_id',
                request_serializer=src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelIdRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelDTO.FromString,
                _registered_method=True)
        self.update_level = channel.unary_unary(
                '/levels.LevelServiceGRPC/update_level',
                request_serializer=src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelUpdateRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.delete_level = channel.unary_unary(
                '/levels.LevelServiceGRPC/delete_level',
                request_serializer=src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelIdRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class LevelServiceGRPCServicer(object):
    """Service definition
    """

    def create_levels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_levels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create_level(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_level_id_by_name(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_level_by_id(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_level(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_level(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LevelServiceGRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create_levels': grpc.unary_unary_rpc_method_handler(
                    servicer.create_levels,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'get_levels': grpc.unary_unary_rpc_method_handler(
                    servicer.get_levels,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelList.SerializeToString,
            ),
            'create_level': grpc.unary_unary_rpc_method_handler(
                    servicer.create_level,
                    request_deserializer=src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'get_level_id_by_name': grpc.unary_unary_rpc_method_handler(
                    servicer.get_level_id_by_name,
                    request_deserializer=src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelRequest.FromString,
                    response_serializer=src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelIdResponse.SerializeToString,
            ),
            'get_level_by_id': grpc.unary_unary_rpc_method_handler(
                    servicer.get_level_by_id,
                    request_deserializer=src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelIdRequest.FromString,
                    response_serializer=src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelDTO.SerializeToString,
            ),
            'update_level': grpc.unary_unary_rpc_method_handler(
                    servicer.update_level,
                    request_deserializer=src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelUpdateRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'delete_level': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_level,
                    request_deserializer=src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelIdRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'levels.LevelServiceGRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('levels.LevelServiceGRPC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LevelServiceGRPC(object):
    """Service definition
    """

    @staticmethod
    def create_levels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/levels.LevelServiceGRPC/create_levels',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_levels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/levels.LevelServiceGRPC/get_levels',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def create_level(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/levels.LevelServiceGRPC/create_level',
            src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_level_id_by_name(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/levels.LevelServiceGRPC/get_level_id_by_name',
            src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelRequest.SerializeToString,
            src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_level_by_id(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/levels.LevelServiceGRPC/get_level_by_id',
            src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelIdRequest.SerializeToString,
            src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update_level(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/levels.LevelServiceGRPC/update_level',
            src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelUpdateRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_level(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/levels.LevelServiceGRPC/delete_level',
            src_dot_grpc_dot_level__service_dot_level__service__pb2.LevelIdRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
