# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/grpc/level_service/level_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*src/grpc/level_service/level_service.proto\x12\x06levels\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"~\n\x08LevelDTO\x12\x12\n\nlang_level\x18\x01 \x01(\t\x12.\n\ncreated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\"\n\x0cLevelRequest\x12\x12\n\nlevel_enum\x18\x01 \x01(\t\"\x1d\n\x0fLevelIdResponse\x12\n\n\x02id\x18\x01 \x01(\t\"-\n\tLevelList\x12 \n\x06levels\x18\x01 \x03(\x0b\x32\x10.levels.LevelDTO\"\"\n\x0eLevelIdRequest\x12\x10\n\x08level_id\x18\x01 \x01(\t\"<\n\x12LevelUpdateRequest\x12\x10\n\x08level_id\x18\x01 \x01(\t\x12\x14\n\x0cupdated_data\x18\x02 \x01(\t*C\n\tLevelEnum\x12\x06\n\x02\x41\x30\x10\x00\x12\x06\n\x02\x41\x31\x10\x01\x12\x06\n\x02\x41\x32\x10\x02\x12\x06\n\x02\x42\x31\x10\x03\x12\x06\n\x02\x42\x32\x10\x04\x12\x06\n\x02\x43\x31\x10\x05\x12\x06\n\x02\x43\x32\x10\x06\x32\xd2\x03\n\x10LevelServiceGRPC\x12?\n\rcreate_levels\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x37\n\nget_levels\x12\x16.google.protobuf.Empty\x1a\x11.levels.LevelList\x12<\n\x0c\x63reate_level\x12\x14.levels.LevelRequest\x1a\x16.google.protobuf.Empty\x12\x45\n\x14get_level_id_by_name\x12\x14.levels.LevelRequest\x1a\x17.levels.LevelIdResponse\x12;\n\x0fget_level_by_id\x12\x16.levels.LevelIdRequest\x1a\x10.levels.LevelDTO\x12\x42\n\x0cupdate_level\x12\x1a.levels.LevelUpdateRequest\x1a\x16.google.protobuf.Empty\x12>\n\x0c\x64\x65lete_level\x12\x16.levels.LevelIdRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.grpc.level_service.level_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEVELENUM']._serialized_start=456
  _globals['_LEVELENUM']._serialized_end=523
  _globals['_LEVELDTO']._serialized_start=116
  _globals['_LEVELDTO']._serialized_end=242
  _globals['_LEVELREQUEST']._serialized_start=244
  _globals['_LEVELREQUEST']._serialized_end=278
  _globals['_LEVELIDRESPONSE']._serialized_start=280
  _globals['_LEVELIDRESPONSE']._serialized_end=309
  _globals['_LEVELLIST']._serialized_start=311
  _globals['_LEVELLIST']._serialized_end=356
  _globals['_LEVELIDREQUEST']._serialized_start=358
  _globals['_LEVELIDREQUEST']._serialized_end=392
  _globals['_LEVELUPDATEREQUEST']._serialized_start=394
  _globals['_LEVELUPDATEREQUEST']._serialized_end=454
  _globals['_LEVELSERVICEGRPC']._serialized_start=526
  _globals['_LEVELSERVICEGRPC']._serialized_end=992
# @@protoc_insertion_point(module_scope)
