# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from src.grpc.user_service import user_service_pb2 as src_dot_grpc_dot_user__service_dot_user__service__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in src/grpc/user_service/user_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class UserServiceGRPCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_user_by_id = channel.unary_unary(
                '/user_service.UserServiceGRPC/get_user_by_id',
                request_serializer=src_dot_grpc_dot_user__service_dot_user__service__pb2.UserIdRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_user__service_dot_user__service__pb2.UserCreateFullDTOResponse.FromString,
                _registered_method=True)
        self.get_user_by_name = channel.unary_unary(
                '/user_service.UserServiceGRPC/get_user_by_name',
                request_serializer=src_dot_grpc_dot_user__service_dot_user__service__pb2.UserNameRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_user__service_dot_user__service__pb2.UserCreateFullDTOResponse.FromString,
                _registered_method=True)
        self.get_user_id_by_name = channel.unary_unary(
                '/user_service.UserServiceGRPC/get_user_id_by_name',
                request_serializer=src_dot_grpc_dot_user__service_dot_user__service__pb2.UserNameRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_user__service_dot_user__service__pb2.UserIdResponse.FromString,
                _registered_method=True)
        self.update_user_training_length = channel.unary_unary(
                '/user_service.UserServiceGRPC/update_user_training_length',
                request_serializer=src_dot_grpc_dot_user__service_dot_user__service__pb2.UserTrainingLengthRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.is_user_created = channel.unary_unary(
                '/user_service.UserServiceGRPC/is_user_created',
                request_serializer=src_dot_grpc_dot_user__service_dot_user__service__pb2.UserNameRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_user__service_dot_user__service__pb2.CheckResponse.FromString,
                _registered_method=True)
        self.create_user_by_DTO = channel.unary_unary(
                '/user_service.UserServiceGRPC/create_user_by_DTO',
                request_serializer=src_dot_grpc_dot_user__service_dot_user__service__pb2.UserCreateTelegramDTORequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.create_user = channel.unary_unary(
                '/user_service.UserServiceGRPC/create_user',
                request_serializer=src_dot_grpc_dot_user__service_dot_user__service__pb2.UserRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class UserServiceGRPCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_user_by_id(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_user_by_name(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_user_id_by_name(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_user_training_length(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_user_created(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create_user_by_DTO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create_user(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceGRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_user_by_id': grpc.unary_unary_rpc_method_handler(
                    servicer.get_user_by_id,
                    request_deserializer=src_dot_grpc_dot_user__service_dot_user__service__pb2.UserIdRequest.FromString,
                    response_serializer=src_dot_grpc_dot_user__service_dot_user__service__pb2.UserCreateFullDTOResponse.SerializeToString,
            ),
            'get_user_by_name': grpc.unary_unary_rpc_method_handler(
                    servicer.get_user_by_name,
                    request_deserializer=src_dot_grpc_dot_user__service_dot_user__service__pb2.UserNameRequest.FromString,
                    response_serializer=src_dot_grpc_dot_user__service_dot_user__service__pb2.UserCreateFullDTOResponse.SerializeToString,
            ),
            'get_user_id_by_name': grpc.unary_unary_rpc_method_handler(
                    servicer.get_user_id_by_name,
                    request_deserializer=src_dot_grpc_dot_user__service_dot_user__service__pb2.UserNameRequest.FromString,
                    response_serializer=src_dot_grpc_dot_user__service_dot_user__service__pb2.UserIdResponse.SerializeToString,
            ),
            'update_user_training_length': grpc.unary_unary_rpc_method_handler(
                    servicer.update_user_training_length,
                    request_deserializer=src_dot_grpc_dot_user__service_dot_user__service__pb2.UserTrainingLengthRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'is_user_created': grpc.unary_unary_rpc_method_handler(
                    servicer.is_user_created,
                    request_deserializer=src_dot_grpc_dot_user__service_dot_user__service__pb2.UserNameRequest.FromString,
                    response_serializer=src_dot_grpc_dot_user__service_dot_user__service__pb2.CheckResponse.SerializeToString,
            ),
            'create_user_by_DTO': grpc.unary_unary_rpc_method_handler(
                    servicer.create_user_by_DTO,
                    request_deserializer=src_dot_grpc_dot_user__service_dot_user__service__pb2.UserCreateTelegramDTORequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'create_user': grpc.unary_unary_rpc_method_handler(
                    servicer.create_user,
                    request_deserializer=src_dot_grpc_dot_user__service_dot_user__service__pb2.UserRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user_service.UserServiceGRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('user_service.UserServiceGRPC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserServiceGRPC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_user_by_id(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_service.UserServiceGRPC/get_user_by_id',
            src_dot_grpc_dot_user__service_dot_user__service__pb2.UserIdRequest.SerializeToString,
            src_dot_grpc_dot_user__service_dot_user__service__pb2.UserCreateFullDTOResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_user_by_name(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_service.UserServiceGRPC/get_user_by_name',
            src_dot_grpc_dot_user__service_dot_user__service__pb2.UserNameRequest.SerializeToString,
            src_dot_grpc_dot_user__service_dot_user__service__pb2.UserCreateFullDTOResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_user_id_by_name(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_service.UserServiceGRPC/get_user_id_by_name',
            src_dot_grpc_dot_user__service_dot_user__service__pb2.UserNameRequest.SerializeToString,
            src_dot_grpc_dot_user__service_dot_user__service__pb2.UserIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update_user_training_length(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_service.UserServiceGRPC/update_user_training_length',
            src_dot_grpc_dot_user__service_dot_user__service__pb2.UserTrainingLengthRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def is_user_created(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_service.UserServiceGRPC/is_user_created',
            src_dot_grpc_dot_user__service_dot_user__service__pb2.UserNameRequest.SerializeToString,
            src_dot_grpc_dot_user__service_dot_user__service__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def create_user_by_DTO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_service.UserServiceGRPC/create_user_by_DTO',
            src_dot_grpc_dot_user__service_dot_user__service__pb2.UserCreateTelegramDTORequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def create_user(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_service.UserServiceGRPC/create_user',
            src_dot_grpc_dot_user__service_dot_user__service__pb2.UserRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
