# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from src.grpc.word_service import word_service_pb2 as src_dot_grpc_dot_word__service_dot_word__service__pb2

GRPC_GENERATED_VERSION = '1.65.2'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in src/grpc/word_service/word_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class WordServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_words_by_user = channel.unary_unary(
                '/wordservice.WordService/get_words_by_user',
                request_serializer=src_dot_grpc_dot_word__service_dot_word__service__pb2.GetWordsByUserRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_word__service_dot_word__service__pb2.GetListWordsByUserResponse.FromString,
                _registered_method=True)
        self.add_new_word_from_dto = channel.unary_unary(
                '/wordservice.WordService/add_new_word_from_dto',
                request_serializer=src_dot_grpc_dot_word__service_dot_word__service__pb2.AddNewWordFromDtoRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.add_new_word = channel.unary_unary(
                '/wordservice.WordService/add_new_word',
                request_serializer=src_dot_grpc_dot_word__service_dot_word__service__pb2.AddNewWordRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class WordServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_words_by_user(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_new_word_from_dto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_new_word(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WordServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_words_by_user': grpc.unary_unary_rpc_method_handler(
                    servicer.get_words_by_user,
                    request_deserializer=src_dot_grpc_dot_word__service_dot_word__service__pb2.GetWordsByUserRequest.FromString,
                    response_serializer=src_dot_grpc_dot_word__service_dot_word__service__pb2.GetListWordsByUserResponse.SerializeToString,
            ),
            'add_new_word_from_dto': grpc.unary_unary_rpc_method_handler(
                    servicer.add_new_word_from_dto,
                    request_deserializer=src_dot_grpc_dot_word__service_dot_word__service__pb2.AddNewWordFromDtoRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'add_new_word': grpc.unary_unary_rpc_method_handler(
                    servicer.add_new_word,
                    request_deserializer=src_dot_grpc_dot_word__service_dot_word__service__pb2.AddNewWordRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wordservice.WordService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wordservice.WordService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WordService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_words_by_user(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wordservice.WordService/get_words_by_user',
            src_dot_grpc_dot_word__service_dot_word__service__pb2.GetWordsByUserRequest.SerializeToString,
            src_dot_grpc_dot_word__service_dot_word__service__pb2.GetListWordsByUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def add_new_word_from_dto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wordservice.WordService/add_new_word_from_dto',
            src_dot_grpc_dot_word__service_dot_word__service__pb2.AddNewWordFromDtoRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def add_new_word(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wordservice.WordService/add_new_word',
            src_dot_grpc_dot_word__service_dot_word__service__pb2.AddNewWordRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
