# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/grpc/auth_service/auth_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(src/grpc/auth_service/auth_service.proto\"^\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x18\n\x10telegram_user_id\x18\x04 \x01(\t\"5\n\x10RegisterResponse\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"[\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x18\n\x10telegram_user_id\x18\x04 \x01(\t\"2\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x12\n\nexpires_in\x18\x02 \x01(\t\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"[\n\x15ValidateTokenResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08username\x18\x04 \x01(\t2\xa7\x01\n\x0b\x41uthService\x12?\n\x0evalidate_token\x12\x15.ValidateTokenRequest\x1a\x16.ValidateTokenResponse\x12&\n\x05login\x12\r.LoginRequest\x1a\x0e.LoginResponse\x12/\n\x08register\x12\x10.RegisterRequest\x1a\x11.RegisterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.grpc.auth_service.auth_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=44
  _globals['_REGISTERREQUEST']._serialized_end=138
  _globals['_REGISTERRESPONSE']._serialized_start=140
  _globals['_REGISTERRESPONSE']._serialized_end=193
  _globals['_LOGINREQUEST']._serialized_start=195
  _globals['_LOGINREQUEST']._serialized_end=286
  _globals['_LOGINRESPONSE']._serialized_start=288
  _globals['_LOGINRESPONSE']._serialized_end=338
  _globals['_VALIDATETOKENREQUEST']._serialized_start=340
  _globals['_VALIDATETOKENREQUEST']._serialized_end=377
  _globals['_VALIDATETOKENRESPONSE']._serialized_start=379
  _globals['_VALIDATETOKENRESPONSE']._serialized_end=470
  _globals['_AUTHSERVICE']._serialized_start=473
  _globals['_AUTHSERVICE']._serialized_end=640
# @@protoc_insertion_point(module_scope)
