# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.grpc.auth_service import auth_service_pb2 as src_dot_grpc_dot_auth__service_dot_auth__service__pb2

GRPC_GENERATED_VERSION = '1.65.5'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in src/grpc/auth_service/auth_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.validate_token = channel.unary_unary(
                '/AuthService/validate_token',
                request_serializer=src_dot_grpc_dot_auth__service_dot_auth__service__pb2.ValidateTokenRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_auth__service_dot_auth__service__pb2.ValidateTokenResponse.FromString,
                _registered_method=True)
        self.login = channel.unary_unary(
                '/AuthService/login',
                request_serializer=src_dot_grpc_dot_auth__service_dot_auth__service__pb2.LoginRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_auth__service_dot_auth__service__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.register = channel.unary_unary(
                '/AuthService/register',
                request_serializer=src_dot_grpc_dot_auth__service_dot_auth__service__pb2.RegisterRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_auth__service_dot_auth__service__pb2.RegisterResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def validate_token(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'validate_token': grpc.unary_unary_rpc_method_handler(
                    servicer.validate_token,
                    request_deserializer=src_dot_grpc_dot_auth__service_dot_auth__service__pb2.ValidateTokenRequest.FromString,
                    response_serializer=src_dot_grpc_dot_auth__service_dot_auth__service__pb2.ValidateTokenResponse.SerializeToString,
            ),
            'login': grpc.unary_unary_rpc_method_handler(
                    servicer.login,
                    request_deserializer=src_dot_grpc_dot_auth__service_dot_auth__service__pb2.LoginRequest.FromString,
                    response_serializer=src_dot_grpc_dot_auth__service_dot_auth__service__pb2.LoginResponse.SerializeToString,
            ),
            'register': grpc.unary_unary_rpc_method_handler(
                    servicer.register,
                    request_deserializer=src_dot_grpc_dot_auth__service_dot_auth__service__pb2.RegisterRequest.FromString,
                    response_serializer=src_dot_grpc_dot_auth__service_dot_auth__service__pb2.RegisterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def validate_token(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AuthService/validate_token',
            src_dot_grpc_dot_auth__service_dot_auth__service__pb2.ValidateTokenRequest.SerializeToString,
            src_dot_grpc_dot_auth__service_dot_auth__service__pb2.ValidateTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AuthService/login',
            src_dot_grpc_dot_auth__service_dot_auth__service__pb2.LoginRequest.SerializeToString,
            src_dot_grpc_dot_auth__service_dot_auth__service__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AuthService/register',
            src_dot_grpc_dot_auth__service_dot_auth__service__pb2.RegisterRequest.SerializeToString,
            src_dot_grpc_dot_auth__service_dot_auth__service__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
